
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class FormRelGerPes extends javax.swing.JFrame {

    private static FormRelGerPes relUnic;
    private GerPes gp = GerPes.gerGerPes();
    private Pessoa p1 = new Pessoa();

    private FormRelGerPes() {
        initComponents();
    }
    
    public static FormRelGerPes geraRelUnic(){
        if(relUnic == null){
            relUnic = new FormRelGerPes();
        }
        return relUnic;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNormal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPes2 = new javax.swing.JTable();
        btConsPes = new javax.swing.JButton();
        btSelectTab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Geral de Pessoas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        LabelNormal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelNormal.setText("Relatório Geral de Pessoas");

        tabPes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "NOME"
            }
        ));
        tabPes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPes2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabPes2);

        btConsPes.setText("consPes");
        btConsPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsPesActionPerformed(evt);
            }
        });

        btSelectTab.setText("selectTab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(LabelNormal))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btConsPes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSelectTab)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsPes)
                    .addComponent(btSelectTab))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        consTabPes();
    }//GEN-LAST:event_formWindowActivated

    private void tabPes2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPes2MouseClicked
        selectTab();
    }//GEN-LAST:event_tabPes2MouseClicked

    private void btConsPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsPesActionPerformed
        
    }//GEN-LAST:event_btConsPesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelGerPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelGerPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelGerPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelGerPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelGerPes().setVisible(true);
            }
        });
    }
    
        public void selectTab() {
        String valLin = "";

        int posLin = tabPes2.getSelectedRow();

        for (int col = 0; col < tabPes2.getColumnCount(); col++) {
            valLin += tabPes2.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabPes2.getColumnCount()){
                valLin += " - ";
            }
        }

        JOptionPane.showMessageDialog(
                null,
                "O valor da linha é: " + valLin,
                "Captura de linha de tabela",
                1
        );
    }

    public void consTabPes() {
        DefaultTableModel tabModel = (DefaultTableModel) tabPes2.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);

        for (Pessoa p : gp.getBdPes()) {
            tabModel.insertRow(posLin, new Object[]{p.getCpf(), p.getNome()});
            posLin++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNormal;
    private javax.swing.JButton btConsPes;
    private javax.swing.JButton btSelectTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPes2;
    // End of variables declaration//GEN-END:variables
}
