
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barMenuPrincipal = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        itMnCalculadora = new javax.swing.JMenuItem();
        itMnCadPes = new javax.swing.JMenuItem();
        itMnSair = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        itMnRelGerPes = new javax.swing.JMenuItem();
        itMnRelGerPes2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Projeto");

        mnCadastro.setText("Cadastros");

        itMnCalculadora.setText("Calculadora...");
        itMnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCalculadoraActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCalculadora);

        itMnCadPes.setText("Cadastro Pessoas...");
        itMnCadPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadPesActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadPes);

        itMnSair.setText("Sair");
        itMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSairActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnSair);

        barMenuPrincipal.add(mnCadastro);

        mnRelatorio.setText("Relatório");

        itMnRelGerPes.setText("Relatório Geral de Pessoas...");
        itMnRelGerPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelGerPesActionPerformed(evt);
            }
        });
        mnRelatorio.add(itMnRelGerPes);

        itMnRelGerPes2.setText("Relatório 2...");
        itMnRelGerPes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelGerPes2ActionPerformed(evt);
            }
        });
        mnRelatorio.add(itMnRelGerPes2);

        barMenuPrincipal.add(mnRelatorio);

        setJMenuBar(barMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCalculadoraActionPerformed
        FormCalc.geraCalc().setVisible(true);
    }//GEN-LAST:event_itMnCalculadoraActionPerformed

    private void itMnCadPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadPesActionPerformed
        FormCadPes.geraCadPes().setVisible(true);
    }//GEN-LAST:event_itMnCadPesActionPerformed

    private void itMnRelGerPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelGerPesActionPerformed
        FormRelGerPes.geraRelUnic().setVisible(true);
    }//GEN-LAST:event_itMnRelGerPesActionPerformed

    private void itMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairActionPerformed
        sair();
    }//GEN-LAST:event_itMnSairActionPerformed

    private void itMnRelGerPes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelGerPes2ActionPerformed
        FormRelGerPes2.geraRelUnic().setVisible(true);
    }//GEN-LAST:event_itMnRelGerPes2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenuPrincipal;
    private javax.swing.JMenuItem itMnCadPes;
    private javax.swing.JMenuItem itMnCalculadora;
    private javax.swing.JMenuItem itMnRelGerPes;
    private javax.swing.JMenuItem itMnRelGerPes2;
    private javax.swing.JMenuItem itMnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnRelatorio;
    // End of variables declaration//GEN-END:variables
}
