
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//José Antonio - ADS - 2025-2
public class FormCadPes extends javax.swing.JFrame {

    private static FormCadPes cadUnic;
    private GerPes gp = GerPes.gerGerPes();
    private Pessoa p1 = new Pessoa();

    private FormCadPes() {
        initComponents();
    }
    
    public static FormCadPes geraCadPes(){
        if(cadUnic == null){
            cadUnic = new FormCadPes();
        }
        return cadUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btInsPes = new javax.swing.JButton();
        btConsPesCpf = new javax.swing.JButton();
        brAltPesCpf = new javax.swing.JButton();
        btDelPesCpf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoa");

        rtCpf.setText("CPF:");

        rtNome.setText("NOME:");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btInsPes.setText("Inserir");
        btInsPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsPesActionPerformed(evt);
            }
        });

        btConsPesCpf.setText("Consultar CPF");
        btConsPesCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsPesCpfActionPerformed(evt);
            }
        });

        brAltPesCpf.setText("Alterar CPF");
        brAltPesCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brAltPesCpfActionPerformed(evt);
            }
        });

        btDelPesCpf.setText("Deletar CPF");
        btDelPesCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelPesCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rtCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInsPes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btConsPesCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brAltPesCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDelPesCpf)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsPes)
                    .addComponent(btConsPesCpf)
                    .addComponent(brAltPesCpf)
                    .addComponent(btDelPesCpf))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInsPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsPesActionPerformed
        insPes();
        
    }//GEN-LAST:event_btInsPesActionPerformed

    private void btConsPesCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsPesCpfActionPerformed
        consPes();
    }//GEN-LAST:event_btConsPesCpfActionPerformed

    private void brAltPesCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brAltPesCpfActionPerformed
        altPesCpf();
        
    }//GEN-LAST:event_brAltPesCpfActionPerformed

    private void btDelPesCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelPesCpfActionPerformed
        delPesCpf();
        
    }//GEN-LAST:event_btDelPesCpfActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        int resp = JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }//GEN-LAST:event_btSairActionPerformed




    public void delPesCpf() {
        try {
            p1 = new Pessoa();
            p1.setCpf(Integer.parseInt(cxCpf.getText()));

            p1 = gp.delPesCpf(p1);

            if (p1 == null) {
                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa deletada",
                        "DelPes",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa não encontrada",
                        "DelPes",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (NumberFormatException nfe) {
            erroException();
        }
    }

    public void altPesCpf() {
        try {
            p1 = new Pessoa();
            p1.setCpf(Integer.parseInt(cxCpf.getText()));

            p1 = gp.atualizaPesCpf(p1);

            if (p1 != null) {
                cxCpf.setText(Integer.toString(p1.getCpf()));
                cxNome.setText(p1.getNome());

                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa encontrada - Confira os dados",
                        "AltPes",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa não encontrada ",
                        "AltPes",
                        JOptionPane.ERROR_MESSAGE
                );
                cxCpf.setText("");
                cxCpf.requestFocus();
            }

        } catch (NumberFormatException nfe) {
            erroException();
        }
    }

    public void consPes() {

        try {
            p1 = new Pessoa();
            p1.setCpf(Integer.parseInt(cxCpf.getText()));

            p1 = gp.consPesCpf(p1);

            if (p1 != null) {

                cxNome.setText(p1.getNome());

                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa encontrada ",
                        "ConsPes",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "Não encontrada pessoa com esse cpf",
                        "ConsPes",
                        JOptionPane.ERROR_MESSAGE
                );
                cxCpf.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException nfe) {
            erroException();
        }
    }

    public void insPes() {

        try {
            p1 = new Pessoa();

            p1.setCpf(Integer.parseInt(cxCpf.getText()));
            p1.setNome(cxNome.getText());

            p1 = gp.insPes(p1);
            if (p1 != null) {
                JOptionPane.showMessageDialog(
                        null,
                        "Pessoa cadastrada com sucesso!",
                        "Cadastro de Pessoas",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "Já existe uma pessoa com este CPF!",
                        "Cadastro de Pessoas",
                        JOptionPane.ERROR_MESSAGE
                );
                cxCpf.setText("");
                cxCpf.requestFocus();
            }
        } catch (NumberFormatException nfe) {
            erroException();
        }
    }

    public void erroException() {
        JOptionPane.showMessageDialog(
                null,
                "NumberFormatException",
                "Cadastro de Pessoas",
                JOptionPane.ERROR_MESSAGE
        );
        cxCpf.setText("");
        cxCpf.requestFocus();
    }

    public void limpar() {
        cxCpf.setText("");
        cxNome.setText("");
        cxCpf.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadPes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadPes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brAltPesCpf;
    private javax.swing.JButton btConsPesCpf;
    private javax.swing.JButton btDelPesCpf;
    private javax.swing.JButton btInsPes;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtNome;
    // End of variables declaration//GEN-END:variables
}
